[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "https://re7-rema-il93.ariane-suivi-social.net/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
